/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#EFECE4',
        'surface-dim': '#E8E4DA',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FAF8F5',
        'surface-container-low': '#F4F1EA',
        'surface-container': '#EFECE4',
        'surface-container-high': '#E8E4DA',
        'surface-container-highest': '#E0DBD0',
        'on-surface': '#181716',
        'on-surface-variant': '#54504A',
        'inverse-surface': '#181716',
        'inverse-on-surface': '#FAF8F5',
        outline: '#C4BCAE',
        'outline-variant': '#D4CDBF',
        'surface-tint': '#9E7B4F',
        primary: '#9E7B4F',
        'on-primary': '#FFFFFF',
        'primary-container': '#8B693C',
        'on-primary-container': '#FAF8F5',
        'inverse-primary': '#C5A059',
        secondary: '#A68252',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#7D5F34',
        'on-secondary-container': '#FAF8F5',
        tertiary: '#B8935C',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#94723E',
        'on-tertiary-container': '#FAF8F5',
        background: '#F6F3EC',
        'on-background': '#181716',
        'surface-variant': '#E8E4DA',
        'surface-dark': '#181716',
        charcoal: '#22201E',
        'white-pure': '#FFFFFF',
        'white-soft': '#F4F1EA',
        'cream-base': '#F6F3EC',
        'cream-card': '#EFECE4',
        'gold-primary': '#9E7B4F',
        'gold-accent': '#C5A059',
        'dark-obsidian': '#161514',
        'brand-dark': '#181716',
        'brand-muted': '#54504A',
      },
      fontFamily: {
        display: ['Space Grotesk', 'system-ui', 'sans-serif'],
        headline: ['Space Grotesk', 'system-ui', 'sans-serif'],
        sans: ['Plus Jakarta Sans', 'Geist', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        serif: ['Cinzel', 'serif'],
        'label-caps': ['Plus Jakarta Sans', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '20px',
        'section-gap': '56px',
        'container-max': '1320px',
      }
    },
  },
  plugins: [],
}
